[browser]
gatherUsageStats = false

[server]
runOnSave = true
headless = true

[theme]
base = "light"
primaryColor = "#000091"
backgroundColor = "#f7f7f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#242424"
font = "sans serif"
